spring.application.name=payment-gateway
server.port=8081
payment.callback.base.url=https://ccd6-102-210-28-44.ngrok-free.app
nextjs.url=http://localhost:3000
nextjs.internal.secret=c8f9b23a1e4d7f5a9b0c1e3d2f4a6b8c
daraja.base.url=https://sandbox.safaricom.co.ke

